# Initializing GAP...
gap> OnBreak := false;;

gap> MakeReadWriteGVar("ERROR_OUTPUT");

gap> ERROR_OUTPUT := MakeImmutable("*stdout*");;

gap> Display(CALL_WITH_CATCH(function() return 314; end, []));;
Entering GAP_TRY section
Leaving GAP_TRY section
[ true, 314 ]

gap> Display(CALL_WITH_CATCH(function() return [][1]; end, []));;
Entering GAP_TRY section
Error, List Element: <list>[1] must have an assigned value
Caught error in GAP_TRY section
[ false, 0 ]

